USE [master]
GO
/****** Object:  Database [Deal_Change]   Script Date: 09/19/2008 14:15:17 ******/
CREATE DATABASE [Deal_Change] 
	ON  PRIMARY 
		(NAME = N'Deal_Change', FILENAME = N'$(Primary)\Deal_Change.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB ),
	FILEGROUP [Archive] 
	( NAME = N'Archive', FILENAME = N'$(ArcDbFilePath)\Deal_Change.ndf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
	LOG ON 
		(NAME = N'Deal_Change_log', FILENAME = N'$(LogFilePath)\Deal_Change_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
	COLLATE SQL_Latin1_General_CP1_CI_AS
GO
EXEC dbo.sp_dbcmptlevel @dbname=N'Deal_Change', @new_cmptlevel=100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
BEGIN
	EXEC [Deal_Change].[dbo].[sp_fulltext_database] @action = 'disable'
END
GO
ALTER DATABASE [Deal_Change] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Deal_Change] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Deal_Change] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Deal_Change] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Deal_Change] SET ARITHABORT OFF 
GO
ALTER DATABASE [Deal_Change] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Deal_Change] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [Deal_Change] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Deal_Change] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Deal_Change] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Deal_Change] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Deal_Change] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Deal_Change] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Deal_Change] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Deal_Change] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Deal_Change] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Deal_Change] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Deal_Change] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Deal_Change] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Deal_Change] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Deal_Change] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Deal_Change] SET  READ_WRITE 
GO
ALTER DATABASE [Deal_Change] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Deal_Change] SET  MULTI_USER 
GO
ALTER DATABASE [Deal_Change] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Deal_Change] SET DB_CHAINING OFF 
Go
