USE [master]
GO
/****** Object:  Database [Deal_Update]    Script Date: 09/19/2008 14:03:46 ******/
CREATE DATABASE [Deal_Update] 
	ON  PRIMARY 
		(NAME = N'Deal_Update', FILENAME = N'$(Primary)\Deal_Update.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB)
	LOG ON 
		(NAME = N'Deal_Update_log', FILENAME = N'$(LogFilePath)\Deal_Update_log.LDF' , SIZE = 768KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
	COLLATE SQL_Latin1_General_CP1_CI_AS
GO
EXEC dbo.sp_dbcmptlevel @dbname=N'Deal_Update', @new_cmptlevel=100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
BEGIN
	EXEC [Deal_Update].[dbo].[sp_fulltext_database] @action = 'enable'
END
GO
ALTER DATABASE [Deal_Update] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Deal_Update] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Deal_Update] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Deal_Update] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Deal_Update] SET ARITHABORT OFF 
GO
ALTER DATABASE [Deal_Update] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Deal_Update] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [Deal_Update] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Deal_Update] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Deal_Update] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Deal_Update] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Deal_Update] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Deal_Update] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Deal_Update] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Deal_Update] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Deal_Update] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Deal_Update] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Deal_Update] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Deal_Update] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Deal_Update] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Deal_Update] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Deal_Update] SET  READ_WRITE 
GO
ALTER DATABASE [Deal_Update] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Deal_Update] SET  MULTI_USER 
GO
ALTER DATABASE [Deal_Update] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Deal_Update] SET DB_CHAINING OFF 
GO
